### ISSUE TITLE
Wrong coordinates for different image size.

### ISSUE THREAD

**Issue by NuniTelo** [shukshin-ivan/image-coordinates.py#1]
When you try on a image with : zoom =15, w = 768 ,h=512 it gives me wrong coordinates.
Can you help please?

**Comment by ishukshin** [comment]
Have you checked the real width of image? It is 640 pixels wide for h=512. So just set parameter w=640.

**Comment by NuniTelo** [comment]
The width is correct and the height is also correct. When i try with you example on github with image 400x400 and zoom 16 it works. But i cant use an image 400x400 because I am stiching three google tiles wide (256x256).  I am so lost. (Also tried with w=640  but still coordinates are not correct)

**Comment by ishukshin** [comment]
Can you give a link to your staticmap image? When I try to get 768x512, google responds with 640x512 image.
https://maps.googleapis.com/maps/api/staticmap?center=53.4055429,-2.9976502&zoom=15&size=768x512&maptype=satellite&key=KEY

**Comment by NuniTelo** [comment]
https://drive.google.com/open?id=11Dug3bOO5WHxFL_SVvL15DSpurJGNMX-   here is the image...
zoom =15 , lat =41.3275 , lng = 19.8187

**Comment by ishukshin** [comment]
Your image is wrong. Coordinates lead us to the Scanderberg Square (see the zoomed image). Your image has that Square not in the center of image, it is shifted to the left. Check your code, which gets image.
![staticmap](https://user-images.githubusercontent.com/2042805/45518464-45581280-b7ba-11e8-898d-174894d70c7b.png)

**Comment by NuniTelo** [comment]
Thank you so much. I didn't notice that. 😁
